/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import Controladores.*;
import Utilidades.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author andre_000
 */
public class VistaGUI extends javax.swing.JFrame {

    
    private  ISimpleControladorFactory miFabricaControlador = new SimpleControladorFactory();
    private Controlador  miControlador;;
    private DTO_Transaccion dtoTransaccion;
    private DTO_Cliente dtoCliente;
    private DTO_Cuenta dtoCuenta;
    private DTO_Sistema dtoSistema;
    /**
     * Creates new form VistaGUI
     */
    public VistaGUI() {
        this.miControlador = miFabricaControlador.crearControlador();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedor = new javax.swing.JPanel();
        jPanelPrincipal = new javax.swing.JPanel();
        comboBoxDepositar = new javax.swing.JComboBox();
        comboBoxRetirar = new javax.swing.JComboBox();
        comboBoxModificar = new javax.swing.JComboBox();
        comboBoxTipoCambio = new javax.swing.JComboBox();
        comboBoxSaldoActual = new javax.swing.JComboBox();
        comboBoxEstadoCuenta = new javax.swing.JComboBox();
        botonSalir = new javax.swing.JButton();
        botonEstatusCuenta = new javax.swing.JButton();
        botonCrearCuenta = new javax.swing.JButton();
        labelEstadoCuenta = new javax.swing.JLabel();
        labelSaldoActual = new javax.swing.JLabel();
        labelTipoCambio = new javax.swing.JLabel();
        labelModificar = new javax.swing.JLabel();
        labelRetirar = new javax.swing.JLabel();
        labelDepositar = new javax.swing.JLabel();
        botonTransferir = new javax.swing.JButton();
        jPanelCrearCuenta = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        textoApellidos = new javax.swing.JTextField();
        labelApellidos = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        textoEmail = new javax.swing.JTextField();
        textoNumTelefono = new javax.swing.JTextField();
        labelNumTelefono = new javax.swing.JLabel();
        labelPin = new javax.swing.JLabel();
        textoPin = new javax.swing.JTextField();
        textoSaldoInicial = new javax.swing.JTextField();
        labelSaldoInicial = new javax.swing.JLabel();
        botonCrearCuenta1 = new javax.swing.JButton();
        jPanelEstatusCuenta = new javax.swing.JPanel();
        botonMostar = new javax.swing.JButton();
        campoTextoNumCuenta = new javax.swing.JTextField();
        labelNumCuenta = new javax.swing.JLabel();
        jPanelSolicitarCuenta = new javax.swing.JPanel();
        labelNumcuenta = new javax.swing.JLabel();
        textoNumCuenta = new javax.swing.JTextField();
        labelIngreseNumCuenta = new javax.swing.JLabel();
        jPanelSolicitarPin = new javax.swing.JPanel();
        labelPin1 = new javax.swing.JLabel();
        textoNumCuenta2 = new javax.swing.JTextField();
        labelIngresePin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAC");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setName("frameVistaGUI"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanelContenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelContenedor.setPreferredSize(new java.awt.Dimension(291, 213));
        jPanelContenedor.setLayout(new java.awt.CardLayout());

        comboBoxDepositar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Colones ", "USD" }));
        comboBoxDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDepositarActionPerformed(evt);
            }
        });

        comboBoxRetirar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Colones ", "USD" }));

        comboBoxModificar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Correo", "Numero telefono", "Pin" }));

        comboBoxTipoCambio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Compra", "Venta" }));
        comboBoxTipoCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoCambioActionPerformed(evt);
            }
        });

        comboBoxSaldoActual.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Colones ", "USD" }));

        comboBoxEstadoCuenta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Colones ", "USD" }));

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonEstatusCuenta.setText("Estatus cuenta");
        botonEstatusCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEstatusCuentaActionPerformed(evt);
            }
        });

        botonCrearCuenta.setText("Crear cuenta");
        botonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearCuentaActionPerformed(evt);
            }
        });

        labelEstadoCuenta.setText("Estado de cuenta en :");

        labelSaldoActual.setText("Saldo actual en :");

        labelTipoCambio.setText("Tipo cambio USD :");

        labelModificar.setText("Modificar :");

        labelRetirar.setText("Retirar en :");

        labelDepositar.setText("Depositar en :");

        botonTransferir.setText("Transferir ");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDepositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTipoCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSaldoActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEstadoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCrearCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEstatusCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBoxEstadoCuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxSaldoActual, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxDepositar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxRetirar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxModificar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxTipoCambio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(botonTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBoxDepositar)
                    .addComponent(labelDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBoxTipoCambio)
                    .addComponent(labelTipoCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSaldoActual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBoxEstadoCuenta)
                    .addComponent(labelEstadoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCrearCuenta)
                    .addComponent(botonTransferir))
                .addGap(5, 5, 5)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEstatusCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelContenedor.add(jPanelPrincipal, "Principal");

        labelNombre.setText("Nombre");

        textoNombre.setText("E.j Minor Andrés");
        textoNombre.setToolTipText("");
        textoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoNombreMouseClicked(evt);
            }
        });
        textoNombre.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                none(evt);
            }
        });

        textoApellidos.setText("E.j Umaña Murillo");
        textoApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoApellidosMouseClicked(evt);
            }
        });

        labelApellidos.setText("Apellidos");

        labelEmail.setText("E-mail");
        labelEmail.setMaximumSize(new java.awt.Dimension(42, 14));
        labelEmail.setMinimumSize(new java.awt.Dimension(42, 14));

        textoEmail.setText("E.j andresmrllo@gmail.com");
        textoEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoEmailMouseClicked(evt);
            }
        });

        textoNumTelefono.setText("E.j 89779846");
        textoNumTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoNumTelefonoMouseClicked(evt);
            }
        });
        textoNumTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNumTelefonoKeyTyped(evt);
            }
        });

        labelNumTelefono.setText("# telefono");
        labelNumTelefono.setMaximumSize(new java.awt.Dimension(42, 14));
        labelNumTelefono.setMinimumSize(new java.awt.Dimension(42, 14));

        labelPin.setText("Pin");
        labelPin.setMaximumSize(new java.awt.Dimension(42, 14));
        labelPin.setMinimumSize(new java.awt.Dimension(42, 14));

        textoPin.setText("E.j Mqw341");
        textoPin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoPinMouseClicked(evt);
            }
        });

        textoSaldoInicial.setText("000,000,000");
        textoSaldoInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoSaldoInicialMouseClicked(evt);
            }
        });

        labelSaldoInicial.setText("Saldo Inicial");
        labelSaldoInicial.setMaximumSize(new java.awt.Dimension(42, 14));
        labelSaldoInicial.setMinimumSize(new java.awt.Dimension(42, 14));

        botonCrearCuenta1.setText("Crear cuenta");
        botonCrearCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearCuenta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCrearCuentaLayout = new javax.swing.GroupLayout(jPanelCrearCuenta);
        jPanelCrearCuenta.setLayout(jPanelCrearCuentaLayout);
        jPanelCrearCuentaLayout.setHorizontalGroup(
            jPanelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCrearCuentaLayout.createSequentialGroup()
                        .addComponent(labelPin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoPin, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCrearCuentaLayout.createSequentialGroup()
                        .addComponent(labelNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCrearCuentaLayout.createSequentialGroup()
                        .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCrearCuentaLayout.createSequentialGroup()
                        .addComponent(labelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoApellidos))
                    .addGroup(jPanelCrearCuentaLayout.createSequentialGroup()
                        .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botonCrearCuenta1)
                        .addGroup(jPanelCrearCuentaLayout.createSequentialGroup()
                            .addComponent(labelSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textoSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelCrearCuentaLayout.setVerticalGroup(
            jPanelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearCuentaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCrearCuenta1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanelContenedor.add(jPanelCrearCuenta, "crearCuenta");

        botonMostar.setText("Mostrar");
        botonMostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostarActionPerformed(evt);
            }
        });

        campoTextoNumCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTextoNumCuentaKeyTyped(evt);
            }
        });

        labelNumCuenta.setText("Numero de cuenta :");

        javax.swing.GroupLayout jPanelEstatusCuentaLayout = new javax.swing.GroupLayout(jPanelEstatusCuenta);
        jPanelEstatusCuenta.setLayout(jPanelEstatusCuentaLayout);
        jPanelEstatusCuentaLayout.setHorizontalGroup(
            jPanelEstatusCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstatusCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEstatusCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonMostar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEstatusCuentaLayout.createSequentialGroup()
                        .addComponent(labelNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoTextoNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEstatusCuentaLayout.setVerticalGroup(
            jPanelEstatusCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstatusCuentaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanelEstatusCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoTextoNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(botonMostar)
                .addContainerGap())
        );

        jPanelContenedor.add(jPanelEstatusCuenta, "estatusCuenta");

        labelNumcuenta.setText("Numero de cuenta:");

        textoNumCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNumCuentaActionPerformed(evt);
            }
        });
        textoNumCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNumCuentaKeyTyped(evt);
            }
        });

        labelIngreseNumCuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelIngreseNumCuenta.setText("Ingrese su numero de cuenta");

        javax.swing.GroupLayout jPanelSolicitarCuentaLayout = new javax.swing.GroupLayout(jPanelSolicitarCuenta);
        jPanelSolicitarCuenta.setLayout(jPanelSolicitarCuentaLayout);
        jPanelSolicitarCuentaLayout.setHorizontalGroup(
            jPanelSolicitarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSolicitarCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSolicitarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSolicitarCuentaLayout.createSequentialGroup()
                        .addComponent(labelNumcuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNumCuenta))
                    .addGroup(jPanelSolicitarCuentaLayout.createSequentialGroup()
                        .addComponent(labelIngreseNumCuenta)
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSolicitarCuentaLayout.setVerticalGroup(
            jPanelSolicitarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSolicitarCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIngreseNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelSolicitarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanelContenedor.add(jPanelSolicitarCuenta, "card5");

        labelPin1.setText("Pin:");

        textoNumCuenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNumCuenta2ActionPerformed(evt);
            }
        });

        labelIngresePin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelIngresePin.setText("Ingrese su Pin");

        javax.swing.GroupLayout jPanelSolicitarPinLayout = new javax.swing.GroupLayout(jPanelSolicitarPin);
        jPanelSolicitarPin.setLayout(jPanelSolicitarPinLayout);
        jPanelSolicitarPinLayout.setHorizontalGroup(
            jPanelSolicitarPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSolicitarPinLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(labelPin1)
                .addGap(18, 18, 18)
                .addComponent(textoNumCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanelSolicitarPinLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(labelIngresePin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSolicitarPinLayout.setVerticalGroup(
            jPanelSolicitarPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSolicitarPinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIngresePin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelSolicitarPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPin1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNumCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanelContenedor.add(jPanelSolicitarPin, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDepositarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboBoxDepositarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCuentaActionPerformed
        // TODO add your handling code here:
        CardLayout contenedor = (CardLayout) jPanelContenedor.getLayout();
        contenedor.show(jPanelContenedor, "crearCuenta");
    }//GEN-LAST:event_botonCrearCuentaActionPerformed

    private void textoNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoNombreMouseClicked
        // TODO add your handling code here:
        textoNombre.setText(null);
    }//GEN-LAST:event_textoNombreMouseClicked

    private void textoApellidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoApellidosMouseClicked
        // TODO add your handling code here:
        textoApellidos.setText(null);
    }//GEN-LAST:event_textoApellidosMouseClicked

    private void textoEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoEmailMouseClicked
        // TODO add your handling code here:
        textoEmail.setText(null);
    }//GEN-LAST:event_textoEmailMouseClicked

    private void textoNumTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoNumTelefonoMouseClicked
        // TODO add your handling code here:
        textoNumTelefono.setText(null);
    }//GEN-LAST:event_textoNumTelefonoMouseClicked

    private void textoPinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoPinMouseClicked
        // TODO add your handling code here:
        textoPin.setText(null);
    }//GEN-LAST:event_textoPinMouseClicked

    private void textoSaldoInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoSaldoInicialMouseClicked
        // TODO add your handling code here:
        textoSaldoInicial.setText(null);
    }//GEN-LAST:event_textoSaldoInicialMouseClicked

    private void botonCrearCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCuenta1ActionPerformed
        // TODO add your handling code here:
        if( !validarNumTelefono(textoNumTelefono.getText()) 
                || !validarCorreo(textoEmail.getText())
                || !validarNombre(textoNombre.getText())
                || !validarNombre(textoApellidos.getText())
                )
        {
            mostrarMensaje("Correo invalido");
            if(!validarNumTelefono(textoNumTelefono.getText()))
            {
                mostrarMensaje("Numero de telefono invalido");
            }
            if(!validarNombre(textoNombre.getText()))
            {
                 mostrarMensaje("Nombre con problemas");
            }
            if(!validarNombre(textoApellidos.getText()))
            {
                 mostrarMensaje("Apellidos con problemas");
            }
        }
        mostrarPanelPrincipal();
    }//GEN-LAST:event_botonCrearCuenta1ActionPerformed

    private void botonEstatusCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEstatusCuentaActionPerformed
        // TODO add your handling code here:
        CardLayout contenedor = (CardLayout) jPanelContenedor.getLayout();
        contenedor.show(jPanelContenedor, "estatusCuenta");
    }//GEN-LAST:event_botonEstatusCuentaActionPerformed

    private void botonMostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostarActionPerformed
        // TODO add your handling code here:
        mostrarPanelPrincipal();
        
    }//GEN-LAST:event_botonMostarActionPerformed

    private void textoNumCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNumCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNumCuentaActionPerformed

    private void textoNumCuenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNumCuenta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNumCuenta2ActionPerformed

    private void none(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void textoNumTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNumTelefonoKeyTyped
        // TODO add your handling code here:
        keyTypeInt(evt);
    }//GEN-LAST:event_textoNumTelefonoKeyTyped

    private void comboBoxTipoCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoCambioActionPerformed
        try {
            // TODO add your handling code here:
            String s = (String) comboBoxTipoCambio.getSelectedItem();
            System.out.println("\n");
            DTO_Transaccion resultadoDolar =null;
            System.out.println(s);
            dtoTransaccion = new DTO_Transaccion();
            String resultado = "";
            if ("Compra".equals(s))
            {
                    dtoTransaccion.setIndicadorEconomico(IndicadorEconomico.INDICADOR_COMPRA);
                    dtoTransaccion.setFechaInicio(Fecha.getFechaActual());
                    dtoTransaccion.setFechaFinal(Fecha.getFechaActual());
                    dtoTransaccion.setNombreClase("Modelo.FabricaBCCR");
                    resultadoDolar = miControlador.conectarWebService(dtoTransaccion);
                    System.out.println(resultadoDolar.getCompraDolar());
                    resultado ="El valor de la compra del dolar es: \n"+ String.valueOf(resultadoDolar.getCompraDolar());
                    //System.out.println("Resultado: "+miControlador.conectarWebService(dtoTransaccion).getCompraDolar());
                    //mostrarMensaje(resultado);
            }
            else{
                    dtoTransaccion = new DTO_Transaccion();
                    dtoTransaccion.setIndicadorEconomico(IndicadorEconomico.INDICADOR_VENTA);
                    dtoTransaccion.setFechaInicio(Fecha.getFechaActual());
                    dtoTransaccion.setFechaFinal(Fecha.getFechaActual());
                    dtoTransaccion.setNombreClase("Modelo.FabricaBCCR");
                    resultadoDolar = miControlador.conectarWebService(dtoTransaccion);
                    System.out.println(resultadoDolar.getVentaDolar());
                    resultado = "El valor de la venta del dolar es: \n"+String.valueOf(resultadoDolar.getVentaDolar());
            }
            
           mostrarMensaje(resultado);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboBoxTipoCambioActionPerformed

    private void textoNumCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNumCuentaKeyTyped
        // TODO add your handling code here:
        keyTypeInt(evt);
    }//GEN-LAST:event_textoNumCuentaKeyTyped

    private void campoTextoNumCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTextoNumCuentaKeyTyped
        // TODO add your handling code here:
        keyTypeInt(evt);
    }//GEN-LAST:event_campoTextoNumCuentaKeyTyped

    private void mostrarPanelPrincipal()
    {
        CardLayout contenedor = (CardLayout) jPanelContenedor.getLayout();
        contenedor.show(jPanelContenedor, "Principal");
    }
    
    private boolean validarCorreo(String correo)
    {
         Pattern pattern = Pattern.compile(patronCorreo);
 
        // Match the given input against this pattern
        Matcher matcher = pattern.matcher(correo.toLowerCase());
        return matcher.matches();
    };
    
    private boolean validarNumTelefono(String numTelefono)
    {
         Pattern pattern = Pattern.compile(patronNumTelefono);
 
        // Match the given input against this pattern
        Matcher matcher = pattern.matcher(numTelefono);
        return matcher.matches();
    };
    
    private boolean validarNombre(String nombre)
    {
         Pattern pattern = Pattern.compile(patronNombre);
 
        // Match the given input against this pattern
        Matcher matcher = pattern.matcher(nombre);
        return matcher.matches();
    };
    
    private  void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    private void keyTypeInt(java.awt.event.KeyEvent evt)
    {
        char c = evt.getKeyChar();
        if (c <'0' || c>'9') evt.consume();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VistaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearCuenta;
    private javax.swing.JButton botonCrearCuenta1;
    private javax.swing.JButton botonEstatusCuenta;
    private javax.swing.JButton botonMostar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonTransferir;
    private javax.swing.JTextField campoTextoNumCuenta;
    private javax.swing.JComboBox comboBoxDepositar;
    private javax.swing.JComboBox comboBoxEstadoCuenta;
    private javax.swing.JComboBox comboBoxModificar;
    private javax.swing.JComboBox comboBoxRetirar;
    private javax.swing.JComboBox comboBoxSaldoActual;
    private javax.swing.JComboBox comboBoxTipoCambio;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelCrearCuenta;
    private javax.swing.JPanel jPanelEstatusCuenta;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelSolicitarCuenta;
    private javax.swing.JPanel jPanelSolicitarPin;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelDepositar;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEstadoCuenta;
    private javax.swing.JLabel labelIngreseNumCuenta;
    private javax.swing.JLabel labelIngresePin;
    private javax.swing.JLabel labelModificar;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumCuenta;
    private javax.swing.JLabel labelNumTelefono;
    private javax.swing.JLabel labelNumcuenta;
    private javax.swing.JLabel labelPin;
    private javax.swing.JLabel labelPin1;
    private javax.swing.JLabel labelRetirar;
    private javax.swing.JLabel labelSaldoActual;
    private javax.swing.JLabel labelSaldoInicial;
    private javax.swing.JLabel labelTipoCambio;
    private javax.swing.JTextField textoApellidos;
    private javax.swing.JTextField textoEmail;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoNumCuenta;
    private javax.swing.JTextField textoNumCuenta2;
    private javax.swing.JTextField textoNumTelefono;
    private javax.swing.JTextField textoPin;
    private javax.swing.JTextField textoSaldoInicial;
    // End of variables declaration//GEN-END:variables
    @SuppressWarnings("FieldMayBeFinal")
    private static  String patronCorreo ="^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\\.[a-zA-Z]{2,4}$";// "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)(\\.[A-Za-z]{2,})$";
    private static  String  patronNumTelefono = "[0-9]{8}";
    private static  String  patronNombre =  "[A-Z][a-zA-Z]*\\D{3}";
}
